services:
  app:
    image: analistaelmo/cakephp2_composer_app:1.0 
    # image: php:7.1-fpm # Caso queira imagem padrão
    # Caso queira o build com Dockerfile tradicional (sem buildx)
    # build:
    #   context: ./docker/dockerfiles
    #   dockerfile: /PHP&Composer
    container_name: cakephp2_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - cake_network

  nginx:
    image: nginx:stable
    container_name: cakephp2_nginx
    ports:
      - "9000:9000" #xdebug
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - cake_network

  mysql:
    image: bitnami/mysql:5.7
    container_name: cakephp2_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cake_network

networks:
  cake_network:
    driver: bridge

